version: '3'
services:
  tutorial-app:
    build:
      context: .
    volumes:
      - ./.dockervenv:/src/.venv
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true